--
-- PostgreSQL database dump
--

-- Dumped from database version 11.3
-- Dumped by pg_dump version 11.2

-- Started on 2019-06-19 15:54:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 196 (class 1259 OID 24852)
-- Name: account; Type: TABLE; Schema: public; Owner: siemp
--

CREATE TABLE public.account (
    id integer NOT NULL,
    username character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(100) NOT NULL,
    active boolean
);


ALTER TABLE public.account OWNER TO siemp;

--
-- TOC entry 197 (class 1259 OID 24855)
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: siemp
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 25012)
-- Name: actividad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad (
    id bigint NOT NULL,
    nombre character(100),
    descripcion character(200),
    fechainicio date,
    fechafin date,
    estado bigint
);


ALTER TABLE public.actividad OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 24857)
-- Name: catalogo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalogo (
    id integer NOT NULL,
    nombre character(50),
    activo boolean,
    fechacrea time without time zone,
    usercrea character varying(15),
    fechamod timestamp without time zone,
    usermod character varying(15)
);


ALTER TABLE public.catalogo OWNER TO postgres;

--
-- TOC entry 199 (class 1259 OID 24860)
-- Name: cuenta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuenta (
    codigo character varying(30) NOT NULL,
    nombre character varying(100),
    descripcion character varying(200),
    codigoctapadre character varying(30),
    estado boolean
);


ALTER TABLE public.cuenta OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 24863)
-- Name: direccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.direccion (
    id bigint NOT NULL,
    idpersona bigint,
    idtipo bigint,
    direccion character varying(200),
    fechacrea timestamp(4) without time zone,
    usercrea character varying(15),
    fechamod timestamp(4) without time zone,
    usermod character varying(15)
);


ALTER TABLE public.direccion OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 24866)
-- Name: documento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documento (
    id bigint NOT NULL,
    idpersona bigint,
    idtipo integer,
    numero character varying(20),
    fechaexpedicion date,
    fechavence date,
    fechacrea timestamp(4) without time zone,
    usercrea character varying(15),
    fechamod timestamp(4) without time zone,
    usermod character varying(15)
);


ALTER TABLE public.documento OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 24869)
-- Name: item_catalogo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item_catalogo (
    id integer NOT NULL,
    descripcion character(50),
    idcatalogo integer,
    activo boolean,
    fechacrea time without time zone,
    usercrea character varying(15),
    fechamod timestamp without time zone,
    usermod character varying(15)
);


ALTER TABLE public.item_catalogo OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 24872)
-- Name: persona; Type: TABLE; Schema: public; Owner: siemp
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    idtipo integer,
    nomcom character varying(50),
    razsocial character varying(50),
    nombre1 character varying(15),
    nombre2 character varying(15),
    nombre3 character varying(15),
    apellido1 character varying(15),
    apellido2 character varying(15),
    apecasada character varying(15),
    fechacrea timestamp without time zone,
    usercrea character varying(15),
    fechamod timestamp without time zone,
    usermod character varying(15),
    fechanac date,
    sexo character varying(1),
    idestadocivil integer
);


ALTER TABLE public.persona OWNER TO siemp;

--
-- TOC entry 204 (class 1259 OID 24875)
-- Name: proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proyecto (
    id bigint NOT NULL,
    codigo character varying(10),
    nombre character varying(200),
    nombrecorto character varying(20),
    fechaini date,
    fechafin date,
    fechacrea time without time zone,
    usercrea character varying(15),
    fechamod timestamp without time zone,
    usermod character varying(15)
);


ALTER TABLE public.proyecto OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 25026)
-- Name: recurso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recurso (
    id bigint NOT NULL,
    nombre character(100),
    cantidad integer,
    costounitario double precision,
    idactividad bigint
);


ALTER TABLE public.recurso OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 25022)
-- Name: seq_actividad; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_actividad
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_actividad OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 24878)
-- Name: seq_catalogo; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_catalogo
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_catalogo OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 24880)
-- Name: seq_direccion; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_direccion
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_direccion OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 24882)
-- Name: seq_documento; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_documento
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_documento OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 24884)
-- Name: seq_itemcatalogo; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_itemcatalogo
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_itemcatalogo OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 24886)
-- Name: seq_persona; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_persona
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_persona OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 24888)
-- Name: seq_proyecto; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_proyecto
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_proyecto OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 25024)
-- Name: seq_recurso; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_recurso
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_recurso OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 24890)
-- Name: seq_telefono; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_telefono
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_telefono OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 24892)
-- Name: seq_usuario; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq_usuario
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq_usuario OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 24894)
-- Name: telefono; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.telefono (
    id bigint NOT NULL,
    idpersona bigint,
    idtipo integer,
    extension character varying(4),
    numero character varying(15),
    fechacrea timestamp(4) without time zone,
    usercrea character varying(15),
    fechamod timestamp(4) without time zone,
    usermod character varying(15)
);


ALTER TABLE public.telefono OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 24897)
-- Name: token; Type: TABLE; Schema: public; Owner: siemp
--

CREATE TABLE public.token (
    id integer NOT NULL,
    account_id integer,
    token_hash character varying(255) NOT NULL,
    token_type character varying(100),
    ip_address character varying(100),
    description character varying(255),
    created timestamp without time zone,
    expiration timestamp without time zone
);


ALTER TABLE public.token OWNER TO siemp;

--
-- TOC entry 215 (class 1259 OID 24903)
-- Name: token_id_seq; Type: SEQUENCE; Schema: public; Owner: siemp
--

ALTER TABLE public.token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 24905)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    usuario character varying(15),
    idpersona bigint,
    password character varying(50),
    fechacrea timestamp without time zone,
    usercrea character varying(15),
    fechamod timestamp without time zone,
    usermod character varying(15)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 2932 (class 0 OID 24852)
-- Dependencies: 196
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: siemp
--

COPY public.account (id, username, password, email, active) FROM stdin;
1	hzometa	PBKDF2WithHmacSHA512:3072:jyoZ4+LdCQcj2/DGzdR6lTE0Q1XTL7zeaE71JmcPuNe7ao+nc29+rAIKXu5rLq/0pEwSVVhCARnImGtkMytFQA==:lzr7Q30zcnOXrNAUxvxxNIEf3UdpVQAbmOLPIfVZv+0=	henryzometa@gmail.com	t
\.


--
-- TOC entry 2953 (class 0 OID 25012)
-- Dependencies: 217
-- Data for Name: actividad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividad (id, nombre, descripcion, fechainicio, fechafin, estado) FROM stdin;
\.


--
-- TOC entry 2934 (class 0 OID 24857)
-- Dependencies: 198
-- Data for Name: catalogo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalogo (id, nombre, activo, fechacrea, usercrea, fechamod, usermod) FROM stdin;
1	Profesiones                                       	t	23:09:21.946	\N	\N	\N
9	Estados de actividad                              	t	\N	\N	\N	\N
\.


--
-- TOC entry 2935 (class 0 OID 24860)
-- Dependencies: 199
-- Data for Name: cuenta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuenta (codigo, nombre, descripcion, codigoctapadre, estado) FROM stdin;
1	ACTIVO	\N	\N	t
11	Activo Circulante	\N	1	t
111	Cajas	\N	11	t
112	Bancos	\N	11	t
113	Asignaciones	\N	11	t
114	Cuentas por cobrar	\N	11	t
1111	Caja Chica	\N	111	t
1121	Cuentas Corrientes	\N	112	t
1122	Cuentas de Ahorro	\N	112	t
1123	Depositos a Plazo Fijo	\N	112	t
1131	Diocesis de Santa Ana	\N	113	t
1141	Documentos por Cobrar	\N	114	t
1142	Deudores Varios	\N	114	t
\.


--
-- TOC entry 2936 (class 0 OID 24863)
-- Dependencies: 200
-- Data for Name: direccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.direccion (id, idpersona, idtipo, direccion, fechacrea, usercrea, fechamod, usermod) FROM stdin;
\.


--
-- TOC entry 2937 (class 0 OID 24866)
-- Dependencies: 201
-- Data for Name: documento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.documento (id, idpersona, idtipo, numero, fechaexpedicion, fechavence, fechacrea, usercrea, fechamod, usermod) FROM stdin;
\.


--
-- TOC entry 2938 (class 0 OID 24869)
-- Dependencies: 202
-- Data for Name: item_catalogo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item_catalogo (id, descripcion, idcatalogo, activo, fechacrea, usercrea, fechamod, usermod) FROM stdin;
31	En proceso                                        	9	t	\N	\N	\N	\N
30	Sin iniciar                                       	9	t	\N	\N	\N	\N
32	Terminada                                         	9	t	\N	\N	\N	\N
\.


--
-- TOC entry 2939 (class 0 OID 24872)
-- Dependencies: 203
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: siemp
--

COPY public.persona (id, idtipo, nomcom, razsocial, nombre1, nombre2, nombre3, apellido1, apellido2, apecasada, fechacrea, usercrea, fechamod, usermod, fechanac, sexo, idestadocivil) FROM stdin;
\.


--
-- TOC entry 2940 (class 0 OID 24875)
-- Dependencies: 204
-- Data for Name: proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proyecto (id, codigo, nombre, nombrecorto, fechaini, fechafin, fechacrea, usercrea, fechamod, usermod) FROM stdin;
\.


--
-- TOC entry 2956 (class 0 OID 25026)
-- Dependencies: 220
-- Data for Name: recurso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recurso (id, nombre, cantidad, costounitario, idactividad) FROM stdin;
\.


--
-- TOC entry 2949 (class 0 OID 24894)
-- Dependencies: 213
-- Data for Name: telefono; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.telefono (id, idpersona, idtipo, extension, numero, fechacrea, usercrea, fechamod, usermod) FROM stdin;
\.


--
-- TOC entry 2950 (class 0 OID 24897)
-- Dependencies: 214
-- Data for Name: token; Type: TABLE DATA; Schema: public; Owner: siemp
--

COPY public.token (id, account_id, token_hash, token_type, ip_address, description, created, expiration) FROM stdin;
\.


--
-- TOC entry 2952 (class 0 OID 24905)
-- Dependencies: 216
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, usuario, idpersona, password, fechacrea, usercrea, fechamod, usermod) FROM stdin;
\.


--
-- TOC entry 2962 (class 0 OID 0)
-- Dependencies: 197
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: siemp
--

SELECT pg_catalog.setval('public.account_id_seq', 1, true);


--
-- TOC entry 2963 (class 0 OID 0)
-- Dependencies: 218
-- Name: seq_actividad; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_actividad', 1, false);


--
-- TOC entry 2964 (class 0 OID 0)
-- Dependencies: 205
-- Name: seq_catalogo; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_catalogo', 9, true);


--
-- TOC entry 2965 (class 0 OID 0)
-- Dependencies: 206
-- Name: seq_direccion; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_direccion', 1, false);


--
-- TOC entry 2966 (class 0 OID 0)
-- Dependencies: 207
-- Name: seq_documento; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_documento', 1, false);


--
-- TOC entry 2967 (class 0 OID 0)
-- Dependencies: 208
-- Name: seq_itemcatalogo; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_itemcatalogo', 32, true);


--
-- TOC entry 2968 (class 0 OID 0)
-- Dependencies: 209
-- Name: seq_persona; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_persona', 1, true);


--
-- TOC entry 2969 (class 0 OID 0)
-- Dependencies: 210
-- Name: seq_proyecto; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_proyecto', 1, false);


--
-- TOC entry 2970 (class 0 OID 0)
-- Dependencies: 219
-- Name: seq_recurso; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_recurso', 1, false);


--
-- TOC entry 2971 (class 0 OID 0)
-- Dependencies: 211
-- Name: seq_telefono; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_telefono', 1, false);


--
-- TOC entry 2972 (class 0 OID 0)
-- Dependencies: 212
-- Name: seq_usuario; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq_usuario', 1, false);


--
-- TOC entry 2973 (class 0 OID 0)
-- Dependencies: 215
-- Name: token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: siemp
--

SELECT pg_catalog.setval('public.token_id_seq', 1, false);


--
-- TOC entry 2757 (class 2606 OID 24909)
-- Name: account account_email_key; Type: CONSTRAINT; Schema: public; Owner: siemp
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_email_key UNIQUE (email);


--
-- TOC entry 2759 (class 2606 OID 24911)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: siemp
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 2761 (class 2606 OID 24913)
-- Name: account account_username_key; Type: CONSTRAINT; Schema: public; Owner: siemp
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_username_key UNIQUE (username);


--
-- TOC entry 2795 (class 2606 OID 25016)
-- Name: actividad actividad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad
    ADD CONSTRAINT actividad_pkey PRIMARY KEY (id);


--
-- TOC entry 2763 (class 2606 OID 24915)
-- Name: catalogo catalogo_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalogo
    ADD CONSTRAINT catalogo_pk PRIMARY KEY (id);


--
-- TOC entry 2765 (class 2606 OID 24995)
-- Name: cuenta cuenta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_pkey PRIMARY KEY (codigo);


--
-- TOC entry 2767 (class 2606 OID 24917)
-- Name: direccion direccion_persona_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_persona_unique UNIQUE (idpersona, idtipo);


--
-- TOC entry 2769 (class 2606 OID 24919)
-- Name: direccion direccion_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_pk PRIMARY KEY (id);


--
-- TOC entry 2771 (class 2606 OID 24921)
-- Name: documento documento_numero_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documento
    ADD CONSTRAINT documento_numero_unique UNIQUE (idtipo, numero);


--
-- TOC entry 2974 (class 0 OID 0)
-- Dependencies: 2771
-- Name: CONSTRAINT documento_numero_unique ON documento; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON CONSTRAINT documento_numero_unique ON public.documento IS 'No puede repetirse numero de documento';


--
-- TOC entry 2773 (class 2606 OID 24923)
-- Name: documento documento_persona_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documento
    ADD CONSTRAINT documento_persona_unique UNIQUE (idpersona, idtipo);


--
-- TOC entry 2975 (class 0 OID 0)
-- Dependencies: 2773
-- Name: CONSTRAINT documento_persona_unique ON documento; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON CONSTRAINT documento_persona_unique ON public.documento IS 'No puede repetirse tipo de documento por persona';


--
-- TOC entry 2775 (class 2606 OID 24925)
-- Name: documento documento_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documento
    ADD CONSTRAINT documento_pk PRIMARY KEY (id);


--
-- TOC entry 2777 (class 2606 OID 24927)
-- Name: item_catalogo item_catalogo_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_catalogo
    ADD CONSTRAINT item_catalogo_pk PRIMARY KEY (id);


--
-- TOC entry 2779 (class 2606 OID 24929)
-- Name: persona persona_pk; Type: CONSTRAINT; Schema: public; Owner: siemp
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pk PRIMARY KEY (id);


--
-- TOC entry 2781 (class 2606 OID 24931)
-- Name: proyecto proyecto_codigo_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_codigo_unique UNIQUE (codigo);


--
-- TOC entry 2783 (class 2606 OID 24933)
-- Name: proyecto proyecto_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_pk PRIMARY KEY (id);


--
-- TOC entry 2797 (class 2606 OID 25030)
-- Name: recurso recurso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recurso
    ADD CONSTRAINT recurso_pkey PRIMARY KEY (id);


--
-- TOC entry 2785 (class 2606 OID 24935)
-- Name: telefono telefono_persona_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.telefono
    ADD CONSTRAINT telefono_persona_unique UNIQUE (idpersona, idtipo);


--
-- TOC entry 2787 (class 2606 OID 24937)
-- Name: telefono telefono_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.telefono
    ADD CONSTRAINT telefono_pk PRIMARY KEY (id);


--
-- TOC entry 2789 (class 2606 OID 24939)
-- Name: token token_pkey; Type: CONSTRAINT; Schema: public; Owner: siemp
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_pkey PRIMARY KEY (id);


--
-- TOC entry 2791 (class 2606 OID 24941)
-- Name: usuario usuario_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pk PRIMARY KEY (id);


--
-- TOC entry 2793 (class 2606 OID 24943)
-- Name: usuario usuario_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_unique UNIQUE (usuario);


--
-- TOC entry 2810 (class 2606 OID 25031)
-- Name: recurso FK_ACTIVIDAD; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recurso
    ADD CONSTRAINT "FK_ACTIVIDAD" FOREIGN KEY (idactividad) REFERENCES public.actividad(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 2798 (class 2606 OID 24997)
-- Name: cuenta FK_CTAPADRE; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT "FK_CTAPADRE" FOREIGN KEY (codigoctapadre) REFERENCES public.cuenta(codigo) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 2809 (class 2606 OID 25017)
-- Name: actividad FK_ESTADO; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad
    ADD CONSTRAINT "FK_ESTADO" FOREIGN KEY (estado) REFERENCES public.item_catalogo(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 2799 (class 2606 OID 24944)
-- Name: direccion direccion_item_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_item_fk FOREIGN KEY (idtipo) REFERENCES public.item_catalogo(id);


--
-- TOC entry 2800 (class 2606 OID 24949)
-- Name: direccion direccion_persona_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_persona_fk FOREIGN KEY (idpersona) REFERENCES public.persona(id);


--
-- TOC entry 2801 (class 2606 OID 24954)
-- Name: documento documento_item_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documento
    ADD CONSTRAINT documento_item_fk FOREIGN KEY (idtipo) REFERENCES public.item_catalogo(id);


--
-- TOC entry 2802 (class 2606 OID 24959)
-- Name: documento documento_persona_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documento
    ADD CONSTRAINT documento_persona_fk FOREIGN KEY (idpersona) REFERENCES public.persona(id);


--
-- TOC entry 2976 (class 0 OID 0)
-- Dependencies: 2802
-- Name: CONSTRAINT documento_persona_fk ON documento; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON CONSTRAINT documento_persona_fk ON public.documento IS 'd';


--
-- TOC entry 2803 (class 2606 OID 24964)
-- Name: item_catalogo item_catalogo_catalogo_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_catalogo
    ADD CONSTRAINT item_catalogo_catalogo_fk FOREIGN KEY (idcatalogo) REFERENCES public.catalogo(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 2804 (class 2606 OID 24969)
-- Name: persona persona_item_fk; Type: FK CONSTRAINT; Schema: public; Owner: siemp
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_item_fk FOREIGN KEY (idtipo) REFERENCES public.item_catalogo(id);


--
-- TOC entry 2805 (class 2606 OID 24974)
-- Name: telefono telefono_item_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.telefono
    ADD CONSTRAINT telefono_item_fk FOREIGN KEY (idtipo) REFERENCES public.item_catalogo(id);


--
-- TOC entry 2806 (class 2606 OID 24979)
-- Name: telefono telefono_persona_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.telefono
    ADD CONSTRAINT telefono_persona_fk FOREIGN KEY (idpersona) REFERENCES public.persona(id);


--
-- TOC entry 2807 (class 2606 OID 24984)
-- Name: token token_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: siemp
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- TOC entry 2808 (class 2606 OID 24989)
-- Name: usuario usuario_persona_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_persona_fk FOREIGN KEY (idpersona) REFERENCES public.persona(id);


-- Completed on 2019-06-19 15:54:49

--
-- PostgreSQL database dump complete
--

